shell /usr/bin/fish

font_family      Cousine Regular Nerd Font Complete Mono
bold_font        Cousine Bold Nerd Font Complete Mono
italic_font      Cousine Italic Nerd Font Complete Mono
bold_italic_font Cousine Bold Italic Nerd Font Complete
