shell /usr/local/bin/fish --interactive --login

font_family      Cousine Nerd Font Mono Regular
bold_font        Cousine Nerd Font Mono Bold
italic_font      Cousine Nerd Font Mono Italic
bold_italic_font Cousine Nerd Font Mono Bold Italic
